# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cameramap_pb2 as cameramap__pb2


class CameramapStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/cameramap.Cameramap/SayHello',
        request_serializer=cameramap__pb2.HelloRequest.SerializeToString,
        response_deserializer=cameramap__pb2.HelloReply.FromString,
        )
    self.SayGoodBye = channel.unary_unary(
        '/cameramap.Cameramap/SayGoodBye',
        request_serializer=cameramap__pb2.HelloRequest.SerializeToString,
        response_deserializer=cameramap__pb2.HelloReply.FromString,
        )


class CameramapServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayGoodBye(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CameramapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=cameramap__pb2.HelloRequest.FromString,
          response_serializer=cameramap__pb2.HelloReply.SerializeToString,
      ),
      'SayGoodBye': grpc.unary_unary_rpc_method_handler(
          servicer.SayGoodBye,
          request_deserializer=cameramap__pb2.HelloRequest.FromString,
          response_serializer=cameramap__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cameramap.Cameramap', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
